name: Build images for app and server

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      name:
        description: "Build"
        default: "test"
        required: true

jobs:
  build_image:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        repository:
          [
            {
              image: "ghcr.io/faddik02/docker-avorion_me:latest",
              path: ".",
            }
          ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image and push
        run: docker buildx build --platform linux/arm64 -t ${{ matrix.repository.image }} --push ${{ matrix.repository.path }}